name: Build with Java 7

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 7 (AdoptOpenJDK)
        uses: actions/setup-java@v3
        with:
          java-version: '7'
          distribution: 'adopt'  # Preferred distribution
          cache: maven

      # OR, if AdoptOpenJDK doesn't work reliably, try Zulu:

      #- name: Set up JDK 7 (Zulu)
      #  uses: actions/setup-java@v3
      #  with:
      #    java-version: '7'
      #    distribution: 'zulu'
      #    cache: maven


      - name: Show Java Version
        run: java -version

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Upload Artifact (WAR file)
        uses: actions/upload-artifact@v4
        with:
          name: jboss-helloworld.war
          path: target/jboss-helloworld.war  # Adjust path if needed