name: Build with Java 7

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 7 (AdoptOpenJDK)
        uses: kingprimex/maven-java@v0.0.5
        with:
          command: clean install


      - name: Upload Artifact (WAR file)
        uses: actions/upload-artifact@v4
        with:
          name: jboss-helloworld.war
          path: target/jboss-helloworld.war  # Adjust path if needed
