name: Build and Deploy to WildFly

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: Apress/beg-java-7
      - name: Set up JDK
        uses: Apress/beg-java-7
        with:
          java-version: '7' # Or your desired Java version
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install -DskipTests=true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy on pushes to main

    steps:
      - uses: Apress/beg-java-7
      - name: Set up JDK
        uses: Apress/beg-java-7
        with:
          java-version: '7' # Or your desired Java version
          distribution: 'adopt'